<a href="https://colab.research.google.com/github/gnsJhenJie/DataScience/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy  
https://numpy.org/

## 1-D Array

In [0]:
import pandas as pd
print("pandas version: %s" % pd.__version__)
import matplotlib
print("matplotlib version: %s" % matplotlib.__version__)
import numpy as np
print("numpy version: %s" % np.__version__)
import sklearn
print("scikit-learn version: %s" % sklearn.__version__)

pandas version: 0.25.3
matplotlib version: 3.1.1
numpy version: 1.17.4
scikit-learn version: 0.21.3


維度（ndim）、形狀（shape）和數值類型（dtype）


In [0]:
np1 = np.array([1, 2, 3])
print(np1.ndim, np1.shape, np1.dtype) 

1 (3,) int64


1 (3,) int64 => 一維陣列, 三個元素, 資料型別

In [0]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
print(x)
print(type(x))
print(x.shape)
print(x.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
int32


np.arange(start, stop, step, dtype)

In [0]:
x = np.arange(5)  #Integer
print (x) 
x = np.arange(5, dtype =  float)  #Float
print (x) 

[0 1 2 3 4]
[0. 1. 2. 3. 4.]


np.linspace 一維等差數列陣列

In [0]:
#  np.linspace(start, stop, 
#       num=50, endpoint=True, retstep=False, dtype=None)

a = np.linspace(1,10,10)
print(a)

a = np.linspace(1,1,10)
print(a)

a = np.linspace(10, 20, 5, endpoint = False)  
print(a)

a = np.linspace(10, 20, 5)  
print(a)

a = np.linspace(10, 20, 5, endpoint = True)  
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[10. 12. 14. 16. 18.]
[10.  12.5 15.  17.5 20. ]
[10.  12.5 15.  17.5 20. ]


np.logspace 一維等比數列陣列

In [0]:
# np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)

a = np.logspace(0,9,10,base=2)
print (a)

[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


## 2-D Array

In [0]:

# import the important module in python 
import numpy as np 
		
# make an array with numpy 
des = np.array([1, 2, 3]) 
src = [4, 5, 6] 
		
# applying numpy.copyto() method 
np.copyto(des, src) 

print(des) 
# import the important module in python 
import numpy as np 
		
# make an array with numpy 
des = np.array([[1, 2, 3], [4, 5, 6]]) 
src = [[4, 5, 6], [7, 8, 9]] 
		
# applying numpy.copyto() method 
np.copyto(des, src) 

print(des) 

[4 5 6]
[[4 5 6]
 [7 8 9]]


In [0]:
ar = np.array([[2,3,4],[9,8,7],[11,12,13]]); 
ar



array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

* Split array

In [0]:
ar[0:1]

array([[2, 3, 4]])

In [0]:
ar[1,0]

9

In [0]:
ar[0,1]

3

## Speed

* Speed of for loop

In [0]:
ar=range(1000)
%timeit [ar[i]**3 for i in ar]

1000 loops, best of 3: 360 µs per loop


* Speed of np array

In [0]:
ar=np.arange(1000)
%timeit ar**3

The slowest run took 10.01 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.54 µs per loop
